<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Domain\Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
      <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.1" />
      <PackageReference Include="MediatR" Version="14.1.0" />
      <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.1.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.26" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.13" />
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
      <PackageReference Include="Serilog.Sinks.Elasticsearch" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.File" Version="8.0.0-nblumhardt-02322" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Features\Admins\Commands\" />
      <Folder Include="Features\Admins\Queries\" />
    </ItemGroup>

</Project>
